Use agoric's synchetic chain image
strangelove-ventures/heighliner pull request #211
Opened 2024-01-20 10:41 UTC by toliaqat

This PR utilizes the Agoric chain's mainnet synthetic chain Docker image from the Agoric-3-proposals repo, rather than replicating the Agoric chain build process. 

Testing was conducted using the following commands.
```
./heighliner build -c agoric -g main
docker run -it --rm --entrypoint sh agoric:main
```

2024-02-16 16:47 UTC, ivanlei requested changes
I've been able to use this successfully but needed to hand edit the agoric docker image to build from

2024-02-16 16:47 UTC, ivanlei commented on dockerfile/agoric/Dockerfile
> +FROM ghcr.io/agoric/agoric-3-proposals:main
@toliaqat - could this be turned into an `ARG AGORIC_BASE_IMAGE` such that someone could run something akin to:
```
heighliner build -c agoric -g main --build-env 'AGORIC_BASE_IMAGE="ghcr.io/agoric/agoric-3-proposals:myprivatetag"
```

2024-03-04 18:45 UTC, agouin commented
Thanks for the PR @toliaqat ! We already have the `imported` dockerfile for this purpose however, which enables building on top of existing docker repository images. We actually built with initially for agoric before we switched to build agoric from source. I think it would be better to switch agoric back to the imported dockerfile and extend the imported dockerfile if necessary than bring in an agoric specific dockerfile.

2024-10-21 13:02 UTC, mrzigha approved these changes

2024-12-04 17:36 UTC, nourspace commented
If still needed please resubmit with new chain files format.

2024-12-04 17:36 UTC, closed without merging